version: '3.5'
services:
  centos_clean:
    image: perfsonar/dev-centos-clean:latest
    build:
        context: .
        dockerfile: Dockerfile
        #args:
        #    repos:
        #        - perfsonar-tools
        #        - perfsonar-testpoint
    tmpfs: 
       - /run
       - /tmp
    volumes:
       - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
       - "8443:443"
    ulimits:
       nproc: 65535
       nofile:
           soft: 20000
           hard: 40000

