version: '3.5'
services:
  toolkit_fresh:
    image: perfsonar/dev-centos-clean:latest
    privileged: true
    build:
        context: .
        dockerfile: Dockerfile
    tmpfs: 
       - /run
       - /tmp
    volumes:
       - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
       - "8443:443"
    ulimits:
       nproc: 65535
       nofile:
           soft: 20000
           hard: 40000

